name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Create Hugo site structure
        run: |
          if [ ! -d "content" ]; then
            mkdir -p content/posts content/about archetypes static themes layouts
            echo '---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
draft: false
tags: []
categories: []
---' > archetypes/default.md
          fi
          
      - name: Download theme
        run: |
          if [ ! -d "themes/PaperMod" ]; then
            git clone https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
          fi
          
      - name: Check for config file
        run: |
          if [ ! -f "config.toml" ]; then
            cat > config.toml << 'EOF'
baseURL = "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
languageCode = "en-us"
title = "AI-Generated Blog"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS"]
  
[params]
  description = "A blog featuring AI-generated content"
  author = "${{ github.repository_owner }}"
  
  [params.homeInfoParams]
    Title = "AI-Generated Content"
    Content = "Exploring ideas through AI-generated articles and podcasts"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/${{ github.repository_owner }}"
    
  [taxonomies]
    category = "categories"
    tag = "tags"
EOF
          fi
          
      - name: Create sample post if none exists
        run: |
          if [ ! "$(ls -A content/posts 2>/dev/null)" ]; then
            cat > content/posts/welcome.md << 'EOF'
---
title: "Welcome to My AI Blog"
date: $(date +%Y-%m-%d)
draft: false
tags: ["welcome", "introduction"]
categories: ["general"]
---

# Welcome to My AI-Generated Blog

This blog features content generated by Claude and Grok, providing unique perspectives on various topics.

## What to Expect

Content here will cover technology, science, philosophy, and more - all created with the assistance of AI.

## Features

- Regular articles on interesting topics
- Podcast versions of popular posts
- Side-by-side comparisons of different AI outputs
EOF
          fi
          
      - name: Build
        run: hugo --minify
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
